name: Build Debian Package
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Package
        run: |
          # Clean version for Debian compatibility (v1.0.0-alpha -> 1.0.0~alpha)
          CLEAN_VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//' | sed 's/-/~/g')
          
          # Create the Debian directory structure
          mkdir -p build/DEBIAN
          mkdir -p build/usr/local/bin
          mkdir -p build/opt/crostini-killer
          mkdir -p build/usr/share/applications
          
          # COPY FROM THE /files/ DIRECTORY
          cp files/crostini-killer.py build/opt/crostini-killer/
          cp files/crostini-killer-config.csv build/opt/crostini-killer/
          
          # Create control file
          cat <<EOF > build/DEBIAN/control
          Package: crostini-killer
          Version: ${CLEAN_VERSION}
          Section: utils
          Priority: optional
          Architecture: all
          Maintainer: cHamster24
          Description: Task killer for Crostini
          EOF

          # Create the terminal launcher wrapper
          echo -e "#!/bin/bash\npython3 /opt/crostini-killer/crostini-killer.py" > build/usr/local/bin/crostini-killer
          chmod +x build/usr/local/bin/crostini-killer

          # Create the desktop shortcut
          echo -e "[Desktop Entry]\nName=Crostini Killer\nExec=crostini-killer\nTerminal=true\nType=Application\nCategories=System;" > build/usr/share/applications/crostini-killer.desktop

          # Build the debian package
          dpkg-deb --build build crostini-killer.deb

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: crostini-killer.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
